language: minimal
services:
  - docker

# We build the package here. Step one builds everything and then step two
# just copies the final file onto the host.
before_install:
  - docker build -t diff .
  - docker run --rm -it --mount "type=bind,src=$(pwd),dst=/host" diff /bin/sh -c "cp /build/diffutils-*.zip /host"

# Display the SHA-256 checksum of the file
before_deploy:
  - sha256sum diffutils-*.zip

deploy:
  provider: releases
  api_key:
    secure: TaYdHDyt3GAIHeKjPIPph91RIOI+idfwVAhQ/vZ+LKtN/RBwlPvKebFkpavPubZzrd1Ru5VHNx+ewpxoKY/+Ml/8X0grIyRnLJFITWLFEhb1MqnadDuWHiUSrixVnehW8IJWy4QcpYcOYApAclD+DmbSJrTCO8WB0bjFcs2yZeR6WiuyNewmW49wwY+d8Kz4HClR4wJXsIMX1nhR/KvlHWii6yUdIxAR6wKqBhVc/42uAWZ7RL1yCyBpaXKVCKaOIZJZq6HIiG1FSviYkwA2KJJJOIupDwigjCZMAbNrD1MA7BZdn2R96u5T8EG5mDh9tyYJaqWOjMh4JrrKJHO8EUr7aqevyE9NXwOoy5qZsft8/Zcqv+Phq7GmR4aMMPlaSbl3LkbO5nBwxYZ0FN+AJVYj5TO+Ri+hdrQTL1KQxHZGjypLuIm2xgerVYkysOcGr0o4K0pQajOLqvM+SWis6Np0X9M5nf9vEmEVda2VfEELdDug6tzLlotCvzMWW3+k3BID8g1ryJGRBltOREgniBk3C3mieIThDC5zvYaJkruVIxF9P9M6BpLFgvvyYHdWLVmKTKd/C9jnVNOGCj8VQKSZPisp9Xy7CZWFTP4ngfu7xBuI2rUznUNTU97i1tUpZDRw8pIW3b5vJtyJJv3RLvNEDG+2oRCuBjIeckTwnnM=
  file_glob: true
  file: "diffutils-*.zip"
  skip_cleanup: true
  on:
    tags: true
